export { default as Header } from "./Header/Header"
export { default as Footer } from "./Footer/Footer"
export { default as Main } from "./Main/Main"
export { default as Card } from "./Card/Card"
export { default as Point } from "./Point/Point"
export { default as LoginPopup } from "./LoginPopup/LoginPopup"
export { default as LoginForm } from "./LoginForm/LoginForm"
export { default as RegisterForm } from "./RegisterForm/RegisterForm"
